### ISSUE TITLE
WalletConnect and Rainbow not loading correctly

### ISSUE THREAD

**Issue by jcstein** [jcstein/rainbowkit-vite-tailwind-starter#2]

**Comment by Dhaiwat10** [comment]
I don't think Rainbow or WalletConnect will work without a websocket connection. If I remember correctly, we don't have websockets for the public plan right? :(

![image](https://user-images.githubusercontent.com/39617427/177042314-9dc5312a-3e85-4fd6-b16a-a9af9849cfb5.png)

**Comment by jcstein** [comment]
That seems right. I also want to see why balances don't load on any network aside ETH mainnet 🤔

**Comment by jcstein** [comment]
hmm - I tried with a WSS and it still doesn't work. want to pair soon on this if we have time
